<a href="https://colab.research.google.com/github/erickgt00/Deep-Learning/blob/main/Practicas/Propagacion_Hacia_Delante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Propagacion hacia delante Deep Learning

In [5]:
import pandas as pd
import numpy as np

1. Una capa de entreda con dos inputs, x1 y x2
2. Una capa oculta con 4 neuronas h1, h2, h3 y h4
3. Una capa de salida con 1 neurona $o_1$

In [7]:
# Inicializar los pesos de las 4 neuronas de la capa oculta

Wxh = np.array([[0.2, 0.65, 0.45,0.12],
                [0.8, 0.35, 0.55, 0.15]])
print(Wxh)

[[0.2  0.65 0.45 0.12]
 [0.8  0.35 0.55 0.15]]


In [8]:
# Inicializar los pesos de la neurona en la capa de salida
Why = np.array([[0.2],
               [0.35],
               [0.45],
               [0.52]])
print(Why)

[[0.2 ]
 [0.35]
 [0.45]
 [0.52]]


In [9]:
# Inicializar los sesgos
bh = np.array([0.2, 0.15, 0.45, 0.23])
by= 0.5
print(bh)

[0.2  0.15 0.45 0.23]


In [10]:
# Definir una función de activación (Sigmoide o Logit)
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [11]:
# Definir la propagación hacia delante
def forward_prop(x):
  z1 = np.dot(x,Wxh)+bh   # Capa Oculta (1x2)(2x4)=(1x4)
  a1 = sigmoid(z1)    # Capa Oculta (1x4)
  z2 = np.dot(a1,Why)+by   # Capa de Salida (1x4)(4x1)=(1x1)
  y_gorro = sigmoid(z2) # Capa de Salida (1x1)
  return y_gorro

In [12]:
# Definir un vector de inputs para estimar y_gorro
x = np.array([1.75,70]) # Altura y peso de una persona
y_gorro = forward_prop(x)
y_gorro

array([0.88288006])

Nuestro $\hat{y}$ puede representar la probabilidad de que sufra una enfermedad o sobre peso, todo esto dependerá de nuestro data set.

# Propagación hacia Atras

In [1]:
import matplotlib.pyplot as plt

Definición de la derivada de la Sigmoide

In [2]:
def sigmoidPrime(x):
  d = (np.exp(-x)) / ((1 + np.exp(-x))**2)
  return d

In [13]:
def back_prop(y_gorro, z1,a1,z2, alpha ):
  global Wxh, Why ,y,dJ_dWxh
  delta2 = np.multiply(-(y-y_gorro), sigmoidPrime(z2)) # 1x1
  dJ_dWhy = np.dot(a1.reshape(4,1) , delta2) # 4 x 1 ) ( 1 x 1 ) 
  delta1= np.dot(delta2, Why.T)*sigmoidPrime(z1) # ( 4x1 ) 
  dJ_dWxh =np.dot(X.reshape(2,1) , delta1.reshape(1,4))
  Wxh = Wxh - alpha * dJ_dWxh
  Why =  Why  - alpha * dJ_dWhy.reshape(4,1)
  return Wxh, Why #Wxh 2 x 4 \\ Why 4x1

In [14]:
#recalcular parametros
X = np.array([1.75,70])
y_gorro = forward_prop(X)
z1  = np.dot(X, Wxh) + bh
a1 = sigmoid(z1)
z2 = np.dot(a1, Why) + by
alpha= 0.025
y = 0.56

In [15]:
back_prop(y_gorro, z1,a1,z2, alpha )

(array([[0.2       , 0.65      , 0.45      , 0.11999999],
        [0.8       , 0.35      , 0.55      , 0.14999946]]),
 array([[0.19916533],
        [0.34916533],
        [0.44916533],
        [0.51916535]]))